# Generated by Django 2.1.1 on 2018-09-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0002_auto_20180924_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.TextField(blank=True, help_text='\nThe path relative to the site root of an image file associated with the news\nitem. This will be used to include the image in the news item card.\n                  '),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True, default='', help_text='\n                  The URL associated with the card image. Where this refers to\nan image from another webiste it must be the full URL, including the scheme\n(http or https), e.g.\n"http://www.nlpca.co.uk/blog/wp-content/uploads/2016/10/Theatre-825x510.jpg".\nFor uploaded images it must be the path to the image relative to the root URL of\nour site, e.g. "/upload/img/2018_09_24-20:18:11.jpg".\n                  '),
        ),
    ]
