# Generated by Django 2.1.1 on 2018-10-18 13:14

from django.db import migrations

def social_media_channels (apps , schema_editor ) :

    # Populate the new social_media_channels table

    Platform = apps.get_model ( 'whatson' , 'SocialMediaPlatform' )

    platform = Platform (
        name = 'Twitter' ,
        icon = 'twitter'
    )

    platform . save ( )

def twitter_handles ( apps , schema_editor ) :

    # Populate the new links with the known Twitter handles of member societies

    Organisation = apps.get_model ( 'whatson' , 'Organisation' )
    Platform = apps.get_model ( 'whatson' , 'SocialMediaPlatform' )
    Handle = apps.get_model ( 'whatson' , 'SocialMediaHandle' )

    twitter = Platform.objects.get ( name = 'Twitter' )

    for organisation in Organisation.objects.filter (
        type = 'whatson_society'
    ) :

        if organisation.name == 'Alfreton Male Voice Choir' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@alfretonmvc'
            )

            handle . save ( )

        elif organisation.name == 'Allestree Theatre Group' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@AllestreeAmDram'
            )

            handle . save ( )

        elif organisation.name == 'Belper Musical Theatre' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@BelperMusical'
            )

            handle . save ( )

        elif organisation.name == 'Chellaston Players' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@ChelloPlayers'
            )

            handle . save ( )

        elif organisation.name == 'Dalesmen Male Voice Choir' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@TheDalesmenMVC'
            )

            handle . save ( )

        elif organisation.name == 'Derby Bach Choir' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@derbybachchoir'
            )

            handle . save ( )

        elif organisation.name == 'Derby Cathedral Concerts' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@DerbyCathedral'
            )

            handle . save ( )

        elif organisation.name == 'Derby Choral Union' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@DCU_DerbyChoral'
            )

            handle . save ( )

        elif organisation.name == 'Derby Concert Band' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@DerbyDCB'
            )

            handle . save ( )

        elif organisation.name == 'Derby Gilbert and Sullivan Company' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@DerbyGSC'
            )

            handle . save ( )

        elif organisation.name == 'Derby Shakespeare Theatre Company' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@derbyshakes'
            )

            handle . save ( )

        elif organisation.name == 'Derwent Singers' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@derwentsingers'
            )

            handle . save ( )

        elif organisation.name == 'Duffield Singers' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@DuffieldSing'
            )

            handle . save ( )

        elif organisation.name == 'Fourblokes Theatre Company' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@Fourblokes'
            )

            handle . save ( )

        elif organisation.name == 'Good Companions Stage Society' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@GoodCompsDerby'
            )

            handle . save ( )

        elif organisation.name == 'Kaleidoscope Players' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@KPlayersDerby'
            )

            handle . save ( )

        elif organisation.name == 'Marlowe Players' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@MarlowePlayers'
            )

            handle . save ( )

        elif organisation.name == 'Mickleover Players' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@Mickieplayers'
            )

            handle . save ( )

        elif organisation.name == 'Quarndon Amateur Dramatic Society' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@QuarndonQuads'
            )

            handle . save ( )

        elif organisation.name == 'Rolleston Choral' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@RollestonChoral'
            )

            handle . save ( )

        elif organisation.name == 'Rose Hill Musical Society' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@RoseHillGandS'
            )

            handle . save ( )

        elif organisation.name == 'Sitwell Singers' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@sitwellsingers'
            )

            handle . save ( )

        elif organisation.name == 'The Derventio Choir' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@derventiochoir'
            )

            handle . save ( )

        elif organisation.name == 'Willington Players' :

            handle = Handle (
                organisation = organisation ,
                platform = twitter ,
                handle = '@WillingtonPlay'
            )

            handle . save ( )

class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0008_auto_20181018_1615'),
    ]

    operations = [
        migrations.RunPython ( social_media_channels ) ,
        migrations.RunPython ( twitter_handles ) ,
    ]
