# Generated by Django 2.1.1 on 2018-10-21 12:50

from django.db import migrations

def event_status ( apps , schema_editor ) :

    # Update event states to new, clearer values

    Event = apps.get_model ( 'whatson' , 'Event' )

    for event in Event.objects.all ( ) :

        if event . status == 'CONFIRMED' :

            event . status = 'PUBLISHED'

            event . save ( )

        elif event . status == 'PLACEHOLDER' :

            event . status = 'DRAFT'

            event . save ( )

        else :

            raise ValueError ( 'Unexpected event status detected' )

class Migration(migrations.Migration):

    dependencies = [
        ('whatson', '0010_auto_20181021_0955'),
    ]

    operations = [
        migrations.RunPython ( event_status ) ,
    ]
